version: '2.2'
services:

  django:
    build: .
    # Loading the app is defined here to allow for
    # autoreload on changes it is mounted on top of the
    # old copy that docker added when creating the image
    volumes:
      - '.:/usr/src/app'
    environment:
      - DEBUG=False
      - GEONODE_LB_HOST_IP=geoportal.vntt.com.vn
      - GEONODE_LB_PORT=80
      - SITEURL=http://geoportal.vntt.com.vn/
      - ALLOWED_HOSTS=['localhost', 'geoportal.vntt.com.vn']
      - GEOSERVER_PUBLIC_LOCATION=http://geoportal.vntt.com.vn/geoserver/
      - GEOSERVER_WEB_UI_LOCATION=http://geoportal.vntt.com.vn/geoserver/

  celery:
    build: .
    environment:
      - DEBUG=False
      - GEONODE_LB_HOST_IP=geoportal.vntt.com.vn
      - GEONODE_LB_PORT=80
      - SITEURL=http://geoportal.vntt.com.vn/
      - ALLOWED_HOSTS=['localhost', 'geoportal.vntt.com.vn']
      - GEOSERVER_PUBLIC_LOCATION=http://geoportal.vntt.com.vn/geoserver/
      - GEOSERVER_WEB_UI_LOCATION=http://geoportal.vntt.com.vn/geoserver/

  geoserver:
    environment:
      - GEONODE_LB_HOST_IP=geoportal.vntt.com.vn
      - GEONODE_LB_PORT=80

  db:
    ports:
      - 5443:5432
