# Generated by Django 2.2.16 on 2021-08-27 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0029_delete_mapsnapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maplayer',
            name='ows_url',
            field=models.URLField(blank=True, max_length=250, null=True, verbose_name='ows URL'),
        ),
    ]
